# fly.toml app configuration file generated for dbd-backend on 2024-02-01T17:23:35+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dbd-backend'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
